import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
export const root='https://www.isiltiplastik.com/tr/urunlerimiz.php';
export function canonical(raw,base=root){try{const u=new URL(raw,base);if(!['www.isiltiplastik.com','isiltiplastik.com'].includes(u.hostname)||!['https:','http:'].includes(u.protocol))return null;u.protocol='https:';u.hostname='www.isiltiplastik.com';u.hash='';return u.href}catch{return null}}
export function pageURL(raw){const u=canonical(raw);return u&&/\/tr\/urunlerimiz(?:detay|icdetay|detaylar)?\.php(?:\?|$)/.test(u)?u:null}
export function assetURL(raw){const u=canonical(raw);return u&&(/\/products(?:detail)?\//i.test(u)||/\.(?:pdf|docx?|xlsx?|zip|rar|dwg|dxf|jpg|jpeg|png|webp|avif)(?:\?|$)/i.test(u))?u:null}
export function signature(b,type){return type.startsWith('image/')?b.length>16&&((b[0]===137&&b[1]===80)||(b[0]===255&&b[1]===216)||b.subarray(0,4).toString()==='RIFF'||b.subarray(4,8).toString()==='ftyp'||b.subarray(0,3).toString()==='GIF'):b.length>0&&!/^\s*(?:<!doctype html|<html)/i.test(b.subarray(0,100).toString())}
export function atomic(file,obj){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(obj,null,2));fs.renameSync(file+'.tmp',file)}
async function run(){
 const {chromium}=await import('playwright');const dir=path.resolve(process.env.CATALOG_DIR||'catalog');fs.mkdirSync(dir,{recursive:true});const stateFile=path.join(dir,'state.json');const state=fs.existsSync(stateFile)?JSON.parse(fs.readFileSync(stateFile)): {queue:[root],done:{},assets:{},errors:{},attempts:{},createdAt:new Date().toISOString()};
 const seeds=JSON.parse(fs.readFileSync(new URL('./seed-ids.json',import.meta.url)));for(const id of seeds){const u='https://www.isiltiplastik.com/tr/urunlerimizdetaylar.php?id='+id;if(!state.done[u]&&!state.queue.includes(u))state.queue.push(u)};const start=Date.now(),maxMs=Number(process.env.MAX_MINUTES||90)*60000,maxBytes=Number(process.env.MAX_BYTES||1073741824);let bytes=Object.values(state.assets).reduce((s,a)=>s+(a.bytes||0),0);let stopReason='';
 for(const [u,a] of Object.entries(state.assets)){if(!fs.existsSync(path.join(dir,a.file))){delete state.assets[u];for(const [p,d] of Object.entries(state.done))if(d.assetUrls.includes(u)){delete state.done[p];if(!state.queue.includes(p))state.queue.push(p)}}}
 const browser=await chromium.launch({headless:true});const context=await browser.newContext();const page=await context.newPage();
 const checkpoint=()=>{state.updatedAt=new Date().toISOString();atomic(stateFile,state);const summary={updatedAt:state.updatedAt,complete:state.queue.length===0&&Object.keys(state.errors).length===0,pages:Object.keys(state.done).length,products:Object.values(state.done).filter(d=>d.url.includes('urunlerimizdetaylar.php')).length,downloadedAssets:Object.keys(state.assets).length,bytes,pending:state.queue.length,errors:state.errors,stopReason};atomic(path.join(dir,'status.json'),summary);console.log(JSON.stringify(summary));if(process.env.GITHUB_STEP_SUMMARY)fs.writeFileSync(process.env.GITHUB_STEP_SUMMARY,'## KEYİF PARK katalog aktarımı\n```json\n'+JSON.stringify(summary,null,2)+'\n```\n')};
 try{while(state.queue.length&&Date.now()-start<maxMs&&bytes<maxBytes){const url=state.queue[0];if(state.done[url]){state.queue.shift();continue}state.attempts[url]=(state.attempts[url]||0)+1;
 try{await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await page.locator('h2').first().waitFor({timeout:20000});const record=await page.evaluate(()=>({url:location.href,title:Array.from(document.querySelectorAll('h2')).map(e=>e.innerText),text:document.body.innerText,html:document.documentElement.outerHTML,links:Array.from(document.querySelectorAll('a')).map(a=>({text:a.textContent.trim(),href:a.href})),images:Array.from(document.images).map(i=>({src:i.src,srcset:i.srcset,width:i.naturalWidth,height:i.naturalHeight}))}));
 if(!record.text.includes('Ürün')||record.text.includes('Verify you are human'))throw Error('Ürün içeriği doğrulanamadı; erişim kontrolü olabilir');
 for(const l of record.links){const p=pageURL(l.href);if(p&&!state.done[p]&&!state.queue.includes(p))state.queue.push(p)}
 const candidates=new Set();for(const i of record.images){if(/\/products(?:detail)?\//i.test(i.src)){candidates.add(canonical(i.src));for(const part of i.srcset.split(',')){const s=part.trim().split(/\s+/)[0];if(s)candidates.add(canonical(s,url))}}}for(const l of record.links){const a=assetURL(l.href);if(a&&!pageURL(a)&&(/\/products(?:detail)?\//i.test(a)||/\.(pdf|docx?|xlsx?|zip|rar|dwg|dxf)(\?|$)/i.test(a)))candidates.add(a)}
 record.assetUrls=[...candidates].filter(Boolean);let assetFailed=false;
 for(const a of record.assetUrls){if(state.assets[a])continue;if(bytes>=maxBytes){assetFailed=true;stopReason='Depolama sınırına ulaşıldı';break}try{const res=await context.request.get(a,{timeout:45000});if(!res.ok())throw Error('HTTP '+res.status());const type=(res.headers()['content-type']||'').split(';')[0];const body=await res.body();if(!signature(body,type))throw Error('Geçersiz dosya içeriği');if(bytes+body.length>maxBytes)throw Error('Depolama sınırı');const hash=crypto.createHash('sha256').update(body).digest('hex');let ext=path.extname(new URL(a).pathname).replace(/[^.a-z0-9]/gi,'')||'.bin';const file='originals/'+hash+ext;fs.mkdirSync(path.join(dir,'originals'),{recursive:true});fs.writeFileSync(path.join(dir,file),body);state.assets[a]={file,source:a,contentType:type,bytes:body.length,sha256:hash,downloadedAt:new Date().toISOString()};bytes+=body.length;delete state.errors[a];atomic(stateFile,state)}catch(e){state.errors[a]=String(e);assetFailed=true}}
 const id=crypto.createHash('sha256').update(url).digest('hex').slice(0,16);fs.mkdirSync(path.join(dir,'pages'),{recursive:true});fs.writeFileSync(path.join(dir,'pages',id+'.html'),record.html);delete record.html;atomic(path.join(dir,'pages',id+'.json'),record);
 if(assetFailed)throw Error('Bazı kaynak dosyalar alınamadı');state.done[url]={url,record:'pages/'+id+'.json',assetUrls:record.assetUrls};delete state.errors[url];state.queue.shift();
 }catch(e){state.errors[url]=String(e);state.queue.shift();if(state.attempts[url]<3)state.queue.push(url)}checkpoint();await new Promise(r=>setTimeout(r,800));}
 if(Date.now()-start>=maxMs)stopReason='Oturum süre sınırı; kayıtlı kuyruktan sürdürülebilir';if(bytes>=maxBytes)stopReason='Depolama sınırı';
 }finally{checkpoint();await browser.close()}
 if(Object.keys(state.errors).length)process.exitCode=2;
}
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1')))await run();

